MODEL:
  META_ARCHITECTURE: "Multi_MetaArch"
  PROPOSAL_GENERATOR:
    NAME: "RPN"  
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
  BACKBONE:
    FREEZE_AT: 3
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN: ("coco_2017_train",) #("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  IMS_PER_BATCH: 4 #16
  BASE_LR: 0.0004 #0.004 #0.02
  STEPS: (250000,) #(30000, 40000) #(56000,) #(60000, 80000) #what's this for?
  MAX_ITER: 300000 #120000 #300000 #45000 #60000 #90000
  WARMUP_ITERS: 1000 #500
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 20000
  # HEAD_LR_FACTOR: 2.0
  #WEIGHT_DECAY_BIAS: 0.0
INPUT:
  # FS:
  #   SUPPORT_WAY: 2
  #   SUPPORT_SHOT: 10
  MIN_SIZE_TRAIN: (440, 472, 504, 536, 568, 600) #(600,) #(640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VERSION: 2
